name: Docs / Link & Lint

on:
  push:
    paths:
      - "**/*.md"
      - ".github/workflows/docs-link-check.yml"
  pull_request:
    paths:
      - "**/*.md"

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Link check (lychee)
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: --verbose --no-progress --exclude-mail --max-concurrency 8 "**/*.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Markdownlint
        uses: avto-dev/markdown-lint@v1
        with:
          config: ".markdownlint.json"
          args: "."
